name: CI/CD
on:
  push:
    branches:
    - master
  pull_request_target:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
    steps:
      - name: Checkout (push)
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v3
      # Separate checkout action for pull_request_target, which needs to
      # explicitly checkout the SHA
      - name: Checkout (pull request)
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '20.9'
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: test
        run: npm run test
      - name: Tag
        if: |
          github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: ./tag.sh
